; Surcharges développement
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

; Xdebug (décommenter si installé dans le Dockerfile)
; xdebug.mode = debug
; xdebug.client_host = host.docker.internal
; xdebug.client_port = 9003
; xdebug.start_with_request = yes

display_errors = On
error_reporting = E_ALL
