twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
    form_themes:
        - 'admin/form/media_file_theme.html.twig'
        - 'bootstrap_5_horizontal_layout.html.twig'
#    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
