version: '3.8'

# Surcharges de développement uniquement
services:
  php:
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
    volumes:
      - ./docker/php/php.dev.ini:/usr/local/etc/php/conf.d/zzz-app-dev.ini:ro

  nginx:
    ports:
      - "8080:80"

  database:
    ports:
      - "3307:3306"

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

  sass:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html:rw
      - vendor:/var/www/html/vendor
      - var:/var/www/html/var
    entrypoint: ["docker-php-entrypoint"]
    command: php bin/console sass:build --watch
    depends_on:
      - php
